server:
  port: 8080

spring:
  application:
    name: auto-reload-app

management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: loggers,refresh
    enabled-by-default: true
